### ISSUE TITLE
Wording...

### ISSUE THREAD

**Issue by rleonid** [UnixJunkie/bisec-tree#11]
I'm a little puzzled by the wording in the README:

> A bisector tree allows to do fast **but** exact nearest neighbor 

isn't 'exact nearest neighbor' what we want, so it'd be better to say:

> A bisector tree allows to do fast and exact nearest neighbor

or, and I've only read the abstract so it isn't clear but is it actual an inexact nearest neighbor?

**Comment by UnixJunkie** [comment]
I was meaning: exact in comparison to approximate methods.
Approximate methods can be way faster and sufficient for many use cases.
However, this implementation is about fast _and_ exact queries.

**Comment by UnixJunkie** [comment]
I updated the README.

**Comment by rleonid** [comment]
Makes sense, thank you.
