### ISSUE TITLE
corner case

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/bisec-tree#9]
P.dist vp1 vp2 = 0.0
then all remaining points must be put into the same bucket; this bucket might have a size > k

**Comment by UnixJunkie** [comment]
done

**Comment by UnixJunkie** [comment]
@hcarty you might be interested in this data structure too

**Comment by UnixJunkie** [comment]
@correnson you too

**Comment by hcarty** [comment]
Thanks!

**Comment by correnson** [comment]
Thanks for the pointer, interesting indeed.

**Comment by UnixJunkie** [comment]
I hope it can cope with millions of points.
The performance is supposed to be better than my vpt implementation.
Maybe the memory usage is better also, due to the buckets of points.
